[package]
name = "extract_token"
version = "0.1.1"
edition = "2021"

[dependencies]
rusty-leveldb = "3.0.0"
serde = { version = "1.0.210", features = ["derive"] }
serde_json = "1.0.128"

[profile.release]
strip = true