format = 4
keep_covers = true
out_path = ""
token = ""
sleep = false
write_covers = true
album_template = "{album_artist} - {album_title}"
track_template = "{track_num_pad}. {title}"
get_original_covers = false
write_lyrics = true
use_ffmpeg_env_var = false